image: node:8.10.0

cache:
  paths:
    - node_modules/
  key: "$CI_PROJECT_ID"

pages:
  stage: deploy
  script:
    - npm install
    - npm run build
    - npm run export
    - mkdir public
    - mv out/* public
    - ls public
  only:
   - master
  artifacts:
    paths:
      - public

